### ISSUE TITLE
Microtxt error?

### ISSUE THREAD

**Issue by valentinbreiz** [CasteSoftworks/CAOS#1]
CAFS.writeText doesn't exist and with that:
string testo = pressed_key.KeyChar.ToString();
var f = File.Create(current_directory + "test.txt");
f.Close();
File.WriteAllText(current_directory + "test.txt", testo);
Micro txt does not save pressed keys :/

**Comment by CasteSoftworks** [comment]
We know, we were able to make it work, but unfrtunatly our PC got fu**ed up and so we lost the working MicroTXT version, now we are re-working on it, stay tuned for news!!
Thanks for being intrested!
